print("Hello")
print("world")
print("this is also a string")
print("I'm going on a run")
print("Hello world one")
print("Hello world two")
print("Hello\tworld")
print(len("hello"))
print(len("I am"))
